= Introduction to directories and files in Groovy
Duncan Dickinson <duncan@groovy-tutorial.org>
v1.0-DRAFT, 2015-10-19
:groovy-version: 2.4.5
:licence: Apache License, Version 2.0
:licence-url: http://www.apache.org/licenses/LICENSE-2.0
:src: https://github.com/groovy-tutorial/basic-files
:sourcedir: ../../main/groovy
:level: basic
:keywords: documentation, manual
:description: This tutorial will provide an introduction to working with directories and folders. A set of basic scripts will be used to demonstrate the various Groovy methods available.
:icons: font
:source-highlighter: coderay
:source-language: groovy
:toc:

Groovy extends the Java file libraries to make reading and writing files really easy.

== Introduction
Reading and writing files and working in the filesystem are cornerstones of most development. Groovy gives us access to the Java libraries for dealing with files and directories and provide some handy methods that take away some heavy lifting. What's more, you can use Groovy scripts to provide quick command line actions that help you manage and manipulate files.

In this tutorial we'll look at directory and file handling by exploring a number of small scripts.

[WARNING]
====
This tutorial is aimed at introducing the topic of reading/writing files and it uses simple code for demonstration purposes.

It's likely that such code will not fare well when facing large files or environments requiring high-performance IO.
====

=== Using this tutorial
For details on running the tutorial on your own system, please refer to the http://www.groovy-tutorial.org/GettingStarted.html[Getting started guide]

Access the source code:

* {src}/tree/gh-pages[Source code]
* {src}/archive/gh-pages.zip[As a zip file]

The source code includes two command line scripts: `run` (for *nix) and `run.bat` (for Windows) - they are very basic helpers that let you run the tutorial scripts via Gradle. To use the `run` scripts just call `run <script>` where `<script>` is the name of the script minus the `.groovy` extension. For example, to run the `directory-list.groovy` script you just use:

    ./run directory-list

A Codenvy project has been setup for this tutorial to make trying it out even easier:  https://codenvy.com/f?id=v6jezb89qakr0um2

TIP: The Codenvy project is easiest to use when running the tutorial code as Groovy scripts but you can also use the Gradle approach but this will cause some downloading to occur.

The code in this tutorial was prepared using Groovy version {groovy-version} and is licensed under {licence-url}[{licence}].

=== Key libraries
The following libraries will be utilised in this tutorial:

* https://docs.oracle.com/javase/8/docs/api/java/nio/file/package-summary.html[Java's `java.nio.file`] provides the primary directory/file handling
** Groovy's extensions to http://docs.groovy-lang.org/latest/html/groovy-jdk/java/nio/file/Path.html[`java.nio.file.Path`] makes life easier
* http://tika.apache.org/[Apache Tika] is used to extract metadata and plain text from files

== Background
Java originally shipped a library (`java.io`) for handling input and output from elements such as files, network resources and devices. A new library, called NIO (`java.nio`), was released in Java 1.4 and extended in Java 7. This later extension is usually referred to as NIO.2 but you'll find these classes in the `java.nio` packages.

As you'd expect, Groovy's home in the JVM lets you use `java.io` and `java.nio` packages. Groovy has a number of enhancements to the `java.io` package and, as of Groovy 2.3, there has been extended (i.e. Groovy-friendly) support for `java.nio.file.Path`. I'll focus on using the NIO packages in the tutorials on file I/O.

=== Key concepts

There are a few key concepts that you should get your head around if you're going to be handling file I/O. First of all, let's picture a filesystem's hierarchical layout:

....
  C:\ or /
  └── users
      ├── bill
      │   └── documents
      │       └── letter.txt
      └── jane
          └── music
              └── song.mp3
....

Whilst this won't necessarily match the way your files are laid out in directories you can see the following in the filesystem:

* The filesystem has a "root" node.
** In Windows this is based on the disk (e.g. `C:\` or `D:\`)
** In Linux and OS X there is only one root node: `/`
* There's a `users` directory.
** Directory is analogous to "folder"
* Each user (`bill` and `jane`) has their own directory
** Bill has one file (`letter.txt`) stored in his `documents` directory
** Jane has one file (`song.mp3`) stored in her `music` directory
* Files usually (though not always) have an extension (e.g. `mp3` or `txt`). This gives us a clue to what type of content to expect in the file
** But don't trust this as the user can change the extension to anything

==== Paths
A "path" defines the location of a resource (such as a file or directory) within a filesystem.

Different operating systems use different notations to define a path. For example, in Linux-based and Apple's OS X operating systems you would refer to Jane's song file using `/users/jane/music/song.mp3`. In Microsoft Windows you would use `C:\users\music\song.mp3`. To separate each segment of the hierarchy (i.e. each folder and file) a separator is used:

 - Linux and OS X use the forward slash character (`/`)
 - Windows uses backslashes (`\`)

[TIP]
====
The use of backslashes in Windows' paths can make strings annoying. Trying `println 'C:\users\jane\music\song.mp3'` in the groovyConsole you'll see the problem pretty quickly - the backslash is an escape character in Groovy strings so that `println` won't work. You can escape the backslash using `\\` but that starts to look very messy: `println 'C:\\users\\jane\\music\\song.mp3'`. Luckily, we can use the forward slash instead and Groovy will not only `println 'C:/users/jane/music/song.mp3'` but understand that your describing a path.

If you'd like to check which separator is used by the operating system you're using, try `println File.separator` in the Groovy Console
====

Paths in some operating systems, such as Linux and OS X, are case-sensitive. This means that you must refer to a path using the correct upper-case and lower-case characters. This means that `/users/Jane/music/song.MP3` doesn't refer to the same path as `/users/jane/music/song.mp3`. However, Windows' paths are case-insensitive so the two versions of the path for Jane's song file both point to the same file. Between this and the different root nodes (`/` and `c:\`) it can be rather frustrating - you can write Groovy code that works across a number of operating systems but you need to make sure you're correctly handling paths.

An _absolute path_ is the canonical location of a file or directory and will contain the root directory (e.g. `C:\` or `/`). For example: `/users/bill/documents/`.

A _relative path_ represents the location of a file/directory from (relative to) another file/directory.

Right, that's enough thoery - let's get to work!

== Directories

Let's start by accessing a directory and determining the files contained within it. In order to do this we'll need:

* `java.nio.file.Paths`: provides static methods for creating an instance of `java.nio.file.Path` based on one or more `String` parameters that, when concatenated, defines a valid path.
** This path doesn't have to actually exist
** `Paths` also works with a URL
* `java.nio.file.Files`: consists of static methods for operating on files and directories.

Let's take a look at a sample script for investigating a directory:

[source]
.link:src/main/groovy/directory-list.groovy[directory-list.groovy]
----
include::{sourcedir}/directory-list.groovy[]
----
<1> The `Paths` class provides a static `get` method in order to create a `Path` instance. Note that `resources` is a relative path under the `src/main/groovy` directory so you need to run the script with `src/main/groovy` as your working directory.
<2> The call to `Files.readAttributes` using the new path instance (`dir`) will give us a map of attributes for the path.
<3> Groovy supplements the Java `Path` class with a very handy `eachFile` method - it will invoke (call) a closure for each child of the path - both files and subdirectories.

[TIP]
.Running the script
====
To run this script you need to change directory into `src/main/groovy` and the run:

    groovy directory-list.groovy

All of the scripts in this tutorial are run from `src/main/groovy` and you just need to change the file name of the script you want to run. If you're using the groovyConsole you should launch it from `src/main/groovy`.
====

You can probably see from the example script that you can really find out a lot about files and directories:

* The `Path` methods provide information about the directory's name (`fileName`) and location (`toAbsolutePath`)
** Don't forget that Groovy lets us access getters in a manner that makes the look like fields/properties - hence `dir.fileName` is really a call to `dir.getFileName()`.
* The `Files` class allows you to create, move, delete, copy and find files and directories. In this example I used it to determine:
** If the directory `exists`,
** The access privileges (`isReadable`, `isWritable`, `isExecutable`), and
** if it's a directory (`isDirectory`)
* The `Files` class can also give us information about the path's attributes such as `creationTime`, `lastModifiedTime`, and `lastAccessTime`.

By calling the `eachFile` method on `dir` I can print out a basic list of the directory's contents. This is a simple example but Groovy methods such as `Path.traverse` and Java's `File.walk` allow code to walk a directory structure.

TIP: See also `Path.eachFileMatch` and `Path.eachFileRecurse` methods when you want to get specific files.

Directory paths let us wander through the filesystem but file paths let us read, create, update and delete content.

== File information

This next example will give us some basic information about the file in terms of its status as a filesystem object.

[source]
.link:src/main/groovy/file-read-info.groovy[file-read-info.groovy]
----
include::{sourcedir}/file-read-info.groovy[]
----
<1> Establish a `Path` instance
<2> Read the file's attributes - much the same as we did in the previous directory example
<3> The `Tika` class is a very useful access point for working with Tika's large set of capabilities.

A lot of the code is quite similar to how the directory was investigated (file path information, access privileges, and attributes).

The call to `tika.detect(f.toFile())` is doing two things:

1. `f.toFile()` provides a representation of the `Path` instance (`f`) using the older `java.io.File` class.
2. The resulting `java.io.File` instance is passed to `tika.detect` returns the media type of the file by opening the file and applying heuristics to determine the type. In the example of `hello.html` the media type is `text/html`.

TIP: Whilst you could also use `println "Content type: ${Files.probeContentType(f)}` to determine the content type it really doesn't work well unless you have an implementation of the `FileTypeDetector` class. I just find the Tika approach easier.

=== File metadata
Many file types contain metadata within the file data. This metadata provides a set of attributes pertaining to the file's content - items such as the author name, the title of a document and so on.

[source]
.link:src/main/groovy/file-read-metadata.groovy[file-read-metadata.groovy]
----
include::{sourcedir}/file-read-metadata.groovy[]
----
<1> Tika's `parse` method will parse the specified file (`resources/xfile.docx`) and load metadata into the `metadata` variable provided. `parse` returns an instance of `java.io.Reader` which Groovy extends with a very handy `getText` method - we'll use this in item 3.
<2> The `metadata.names()` method returns an array of metadata field names that can then be used to obtain the value of each metadata field.
<3> The `Reader` instance (`r`) returned from `parse` lets us access the file's content as plain text.

You'll notice that the script reads a `docx` file, usually produced by Microsoft Word. This is what makes Tike extremely useful - it can read a wide variety of file types and return you the file's metadata and content. In the coming examples I'll read simple text files but many of these examples won't work on other types of files, including `docx`s.

== Reading a file
Groovy makes reading a text file so easy - just get an instance of the `Path` and call the `getText()` method as though it's a field (`text`):

[source]
.link:src/main/groovy/file-read-path.groovy[file-read-path.groovy]
----
include::{sourcedir}/file-read-path.groovy[]
----

This will just output the content of the text file in one go - be warned that this works OK for small files but is not the way to handle large files.

[TIP]
.The old path
====
The `java.io.File` class is in heavy use across the Java-verse but http://www.oracle.com/technetwork/articles/javase/nio-139333.html[it's the old way of doing things]. The example below demonstrates `File` in action:

[source]
.link:src/main/groovy/file-read-file.groovy[file-read-file.groovy]
----
include::{sourcedir}/file-read-file.groovy[]
----

Luckily, the `File` class has a `toPath()` method that you can use to switch to the `nio` path:

[source]
.link:src/main/groovy/file-path-bridge.groovy[file-path-bridge.groovy]
----
include::{sourcedir}/file-path-bridge.groovy[]
----

Walk the new `Path`!
====

=== Using a buffered reader
Groovy provides the `Path` class with a `withReader` method which uses a `java.io.BufferedReader` to read the file - making it a more efficient approach to reading text-based files. A closure is passed to `withReader` and the `BufferedReader` is fed into the closure - the `it` parameter in the example below.

[source]
.link:src/main/groovy/file-read-reader.groovy[file-read-reader.groovy]
----
include::{sourcedir}/file-read-reader.groovy[]
----
<1> This uses `BufferedReader`'s `lines` method to read a line at a time.

Once the closure is finished, Groovy closes the `BufferedReader`.

=== Read each line

Groovy gives the `Path` class an `eachLine` method, allowing you to call a closure on each line in the text file:

[source]
.link:src/main/groovy/file-read-lines.groovy[file-read-lines.groovy]
----
include::{sourcedir}/file-read-lines.groovy[]
----

=== Filter a file
Groovy gives the `Path` class an `filterLine` method that accepts a closure as a parameter and returns the lines that are not filtered out. The closure body performs the filter and returns `true` to keep the line or `false` to ignore it. In the example below all empty lines are stripped out of the text:

[source]
.link:src/main/groovy/file-read-filter.groovy[file-read-filter.groovy]
----
include::{sourcedir}/file-read-filter.groovy[]
----

=== Split a file

Another handy Groovy addition to `Path` is the `splitEachLine` method. The usage below passes in a regular expression (`/,/`) to split the line into fields separated by a comma. Each section returned by this split is loaded into an array that is passed into the closure that forms the second parameter for `splitEachLine`. This closure can then respond to the fields found in each line.

[source]
.link:src/main/groovy/file-read-split.groovy[file-read-split.groovy]
----
include::{sourcedir}/file-read-split.groovy[]
----

TIP: This is just an example of reading a comma-separated (csv) file and a quick web search will locate you one of the many libraries available for correctly handling delimited files such as csv.

== Writing a file

Writing text to a file is extremely easy. As usual, you get a `Path` instance and then call one of a variety of methods. The example below demonstrates two approaches:

[source]
.link:src/main/groovy/file-write-basic.groovy[file-write-basic.groovy]
----
include::{sourcedir}/file-write-basic.groovy[]
----
<1> Groovy adds a `write` method to the `Path` class
<2> Groovy also adds a `setText()` method so that you can set the file's contents as if it was a field.

In both of the examples above if the file doesn't exist then it is created with the text provided. If the file does exist then its content is replaced by the `write` and `setText` methods.

=== Writing a temporary file

It's often handy to write to a temporary file for use as intermediate storage. Most operating systems have a location for storing temporary files and it is usually assumed that you only need the file for a limited time period - i.e. don't use them for long-term storage.

In the example below the call to `Files.createTempFile` creates a new temporary file and then writes to it.

[source]
.link:src/main/groovy/file-write-temp.groovy[file-write-temp.groovy]
----
include::{sourcedir}/file-write-temp.groovy[]
----

TIP: A new temporary file is created each time `Files.createTempFile` is called. This means you don't need to worry about writing over an existing file but it also means that the directory holding the temporary files can get quite large. For programs needing a lot of temporary file storage it's worth looking at `Files.createTempDirectory`.

=== Appending to a file

Sometimes you just want to add content (append) to a file.

[source]
.link:src/main/groovy/file-write-append.groovy[file-write-append.groovy]
----
include::{sourcedir}/file-write-append.groovy[]
----
<1> Use the `write` method to create some original content
<2> The `<<` operator will append to the file

The `<<` operator is backed by the `append` method that Groovy adds to the `Path` class. It's possible to call `f.append('some text')` but the operator approach, to my mind, is more readable.

=== Using a buffered writer

Much as we saw with the `withReader` for easy use of a `BufferedReader`, Groovy provides `withWriter` for easy use of a `BufferedWriter`. This approach can be more efficient when writing out a large amount of content to a file. Groovy will flush and close the writer when the closure completes.

[source]
.link:src/main/groovy/file-write-writer.groovy[file-write-writer.groovy]
----
include::{sourcedir}/file-write-writer.groovy[]
----

Cases in which your code may be reading from one source (e.g. a database or your new Internet of Things gadget) and placing the output into a file are good candidates for `withWriter`.

== Conclusion
This tutorial has provided an introduction to working with directories and files. Naturally, there's a lot more functionality on offer in the Java libraries and it's worth reading both the javadoc for these libraries as well as the javadoc for the Groovy extensions. I plan some more specific tutorials regarding XML, JSON, YAML, CSV and Excel so check back into http://www.groovy-tutorial.org[www.groovy-tutorial.org] to see what's new.

=== Further reading

* https://docs.oracle.com/javase/tutorial/essential/io/[Java Tutorial on Basic I/O]
* http://www.ibm.com/developerworks/java/tutorials/j-nio/j-nio.html[Getting started with new I/O (NIO)]
