= Introduction to directories and files in Groovy
Duncan Dickinson <duncan@groovy-tutorial.org>
v0.1-DRAFT, 2015-09-09
:groovy-version: 2.4.4
:licence: Apache License, Version 2.0
:licence-url: http://www.apache.org/licenses/LICENSE-2.0
:src: https://github.com/groovy-tutorial/basic-files
:sourcedir: ../../main/groovy
:level: basic
:keywords: documentation, manual
:description: This tutorial will provide an introduction to working with directories and folders. A set of basic scripts will be used to demonstrate the various Groovy methods available.
:icons: font
:source-highlighter: coderay
:source-language: groovy
:toc:

Groovy extends the Java file libraries to make reading and writing files really easy.

== Introduction
Reading and writing files and working in the filesystem are cornerstones of most development. Groovy gives us access to the Java libraries for dealing with files and directories and provide some handy methods that take away some heavy lifting. What's more, you can use Groovy scripts to provide quick command line actions that help you manage and manipulate files.

In this tutorial we'll look at directory and file handling by exploring a number of small scripts.

[WARNING]
====
This tutorial is aimed at introducing the topic of reading/writing files and it uses simple code for demonstration purposes.

It's likely that such code will not fare well when facing large files or environments requiring high-performance IO.
====

=== Key libraries
The following libraries will be utilised in this tutorial:

* https://docs.oracle.com/javase/8/docs/api/java/nio/file/package-summary.html[Java's `java.nio.file`] provides the primary directory/file handling
** http://docs.groovy-lang.org/latest/html/groovy-jdk/java/nio/file/Path.html[Groovy's extension to `java.nio.file.Path`] makes life easier
* http://tika.apache.org/[Apache Tika] is used to extract metadata and plain text from files

=== Using this tutorial
For details on running the tutorial on your own system, please refer to the http://www.groovy-tutorial.org/GettingStarted.html[Getting started guide]

Access the source code:

* {src}/tree/gh-pages[Source code]
* {src}/archive/gh-pages.zip[As a zip file]

The code in this tutorial was prepared using Groovy version {groovy-version} and is licensed under {licence-url}[{licence}]

== Background
Java originally shipped a library (`java.io`) for handling input and output from elements such as files, network resources and devices. A new library, called NIO (`java.nio`), was released in Java 1.4 and extended in Java 7. This later extension is usually referred to as NIO.2 but you'll find these classes in the `java.nio` packages.

As you'd expect, Groovy's home in the JVM lets you use `java.io` and `java.nio` packages. Groovy has a number of enhancements to the `java.io` package and, as of Groovy 2.3, there has been extended (i.e. Groovy-friendly) support for `java.nio.file.Path`. I'll focus on using the NIO packages in the tutorials on file I/O.

=== Key concepts

There are a few key concepts that you should get your head around if you're going to be handling file I/O. First of all, let's picture a filesystem's hierarchical layout:

....
  C:\ or /
  └── users
      ├── bill
      │   └── documents
      │       └── letter.txt
      └── jane
          └── music
              └── song.mp3
....

Whilst this won't necessarily match the way your files are laid out in directories you can see the following in the filesystem:

* The filesystem has a "root" node.
** In Windows this is based on the disk (e.g. `C:\` or `D:\`)
** In Linux and OS X there is only one root node: `/`
* There's a `users` directory.
** Directory is analogous to "folder"
* Each user (`bill` and `jane`) has their own directory
** Bill has one file (`letter.txt`) stored in his `documents` directory
** Jane has one file (`song.mp3`) stored in her `music` directory
* Files usually (though not always) have an extension (e.g. `mp3` or `txt`). This gives us a clue to what type of content to expect in the file
** But don't trust this as the user can change the extension to anything

==== Paths
A "path" defines the location of a resource (such as a file or directory) within a filesystem.

Different operating systems use different notations to define a path. For example, in Linux-based and Apple's OS X operating systems you would refer to Jane's song file using `/users/jane/music/song.mp3`. In Microsoft Windows you would use `C:\users\music\song.mp3`. To separate each segment of the hierarchy (i.e. each folder and file) a separator is used:

 - Linux and OS X use the forward slash character (`/`)
 - Windows uses backslashes (`\`)

[TIP]
====
The use of backslashes in Windows' paths can make strings annoying. Trying `println 'C:\users\jane\music\song.mp3'` in the groovyConsole you'll see the problem pretty quickly - the backslash is an escape character in Groovy strings so that `println` won't work. You can escape the backslash using `\\` but that starts to look very messy: `println 'C:\\users\\jane\\music\\song.mp3'`. Luckily, we can use the forward slash instead and Groovy will not only `println 'C:/users/jane/music/song.mp3'` but understand that your describing a path.

If you'd like to check which separator is used by the operating system you're using, try `println File.separator` in the Groovy Console
====

Paths in some operating systems, such as Linux and OS X, are case-sensitive. This means that you must refer to a path using the correct upper-case and lower-case characters. This means that `/users/Jane/music/song.MP3` doesn't refer to the same path as `/users/jane/music/song.mp3`. However, Windows' paths are case-insensitive so the two versions of the path for Jane's song file both point to the same file. Between this and the different root nodes (`/` and `c:\`) it can be rather frustrating - you can write Groovy code that works across a number of operating systems but you need to make sure you're correctly handling paths.

An _absolute path_ is the canonical location of a file or directory and will contain the root directory (e.g. `C:\` or `/`). For example: `/users/bill/documents/`.

A _relative path_ represents the location of a file/directory from (relative to) another file/directory.

== The pratcical stuff

Right, that's enough thoery - let's get to work!

== Directories

[source]
.link:groovy/directory-list.groovy[directory-list.groovy]
----
include::{sourcedir}/directory-list.groovy[]
----
<1> Blah
<2> Blah 2
<3>

TIP: See also `Path.eachFileMatch` and `Path.eachFileRecurse` methods when you want to get specific files.

== Files
=== File information

[source]
.link:groovy/file-read-info.groovy[file-read-info.groovy]
----
include::{sourcedir}/file-read-info.groovy[]
----

[source]
.link:groovy/file-read-metadata.groovy[file-read-metadata.groovy]
----
include::{sourcedir}/file-read-metadata.groovy[]
----

=== Reading a file
Groovy

[source]
.link:groovy/file-read-path.groovy[file-read-path.groovy]
----
include::{sourcedir}/file-read-path.groovy[]
----

[TIP]
.The old path
====
The `java.io.File` class is in heavy use across the Java-verse but http://www.oracle.com/technetwork/articles/javase/nio-139333.html[it's the old way of doing things]. The example below demonstrates `File` in action:

[source]
.link:groovy/file-read-file.groovy[file-read-file.groovy]
----
include::{sourcedir}/file-read-file.groovy[]
----

Luckily, the `File` class has a `toPath()` method that you can use to switch to the `nio` path:

[source]
.link:groovy/file-path-bridge.groovy[file-path-bridge.groovy]
----
include::{sourcedir}/file-path-bridge.groovy[]
----

Walk the new `Path`!
====

[source]
.link:groovy/file-read-reader.groovy[file-read-reader.groovy]
----
include::{sourcedir}/file-read-reader.groovy[]
----

==== Read each line
[source]
.link:groovy/file-read-lines.groovy[file-read-lines.groovy]
----
include::{sourcedir}/file-read-lines.groovy[]
----

[source]
.link:groovy/file-read-filter.groovy[file-read-filter.groovy]
----
include::{sourcedir}/file-read-filter.groovy[]
----

[source]
.link:groovy/file-read-split.groovy[file-read-split.groovy]
----
include::{sourcedir}/file-read-split.groovy[]
----

include::section_writing.adoc[]
